name: RELEASE

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm i --frozen-lockfile

      - name: Run lint
        run: |
          pnpm run lint --no-fix

      - name: Run type check
        run: |
          pnpm run type-check

      - name: Run tests
        run: |
          pnpm run test:unit

      - name: Run circular references check
        run: |
          pnpm run circular-check

      - name: Build
        run: |
          pnpm run build

      - name: Create Artifact
        run: |
          cd ./dist
          zip -r ../fluidd.zip ./

      - name: Get version from tag
        id: tag_name
        run: |
          echo "current_version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Read ChangeLog
        uses: mindsers/changelog-reader-action@v2.2.3
        id: changelog
        with:
          validation_depth: 1
          version: ${{ steps.tag_name.outputs.current_version }}
          path: ./CHANGELOG.md

      - name: Release Firmware Binaries
        uses: softprops/action-gh-release@v2
        with:
          files: ./fluidd.zip
          body: |
            ${{ steps.changelog.outputs.changes }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fluidd-${{ github.sha }}.zip
          path: ./dist
